export const PLACEHOLDER_SUGGESTIONS = [
  'Study React',
  'Fight with MegaLinter',
  'Pick up {children}',
  'Complete PR review',
  'Explore the FKIT framework',
  'Revive Angular',
  'Merge all the conflicts',
  'Master Git-fu',
  'Think in binary, like in ASCII',
  'Make Function calls, not phone calls',
  'Await the asyncs',
  'Abstract the abstractions',
  'Determine if bug or feature',
];
